package com.zhenshiz.betterbook.core;

import java.util.List;

/** 分类公式面板；按钮展示和插入采用相同源码，避免图标与结果不一致。 */
public final class LatexPalette {
    private LatexPalette() {}
    public record Entry(String id, String source) {}
    public record Section(String id, List<Entry> entries) {}
    public record Category(String id, String icon, List<Section> sections) {}
    private static Entry entry(String id, String source) { return new Entry(id, source); }
    private static Section section(String id, Entry... entries) { return new Section(id, List.of(entries)); }
    private static Category category(String id, String icon, Section... sections) { return new Category(id, icon, List.of(sections)); }

    public static final List<Category> CATEGORIES = List.of(
        category("symbols", "\\times\\,\\textcolor{#4d7b32}{\\cap}\\quad\\therefore\\,\\propto",
            section("symbols_binary",
                entry("symbols_binary_plus", "+"),
                entry("symbols_binary_minus", "-"),
                entry("symbols_binary_times", "\\times"),
                entry("symbols_binary_div", "\\div"),
                entry("symbols_binary_pm", "\\pm"),
                entry("symbols_binary_mp", "\\mp"),
                entry("symbols_binary_triangleleft", "\\triangleleft"),
                entry("symbols_binary_triangleright", "\\triangleright"),
                entry("symbols_binary_cdot", "\\cdot"),
                entry("symbols_binary_setminus", "\\setminus"),
                entry("symbols_binary_star", "\\star"),
                entry("symbols_binary_ast", "\\ast"),
                entry("symbols_binary_cup", "\\cup"),
                entry("symbols_binary_cap", "\\cap"),
                entry("symbols_binary_sqcup", "\\sqcup"),
                entry("symbols_binary_sqcap", "\\sqcap"),
                entry("symbols_binary_vee", "\\vee"),
                entry("symbols_binary_wedge", "\\wedge"),
                entry("symbols_binary_circ", "\\circ"),
                entry("symbols_binary_bullet", "\\bullet"),
                entry("symbols_binary_oplus", "\\oplus"),
                entry("symbols_binary_ominus", "\\ominus"),
                entry("symbols_binary_odot", "\\odot"),
                entry("symbols_binary_oslash", "\\oslash"),
                entry("symbols_binary_otimes", "\\otimes"),
                entry("symbols_binary_bigcirc", "\\bigcirc"),
                entry("symbols_binary_diamond", "\\diamond"),
                entry("symbols_binary_uplus", "\\uplus"),
                entry("symbols_binary_bigtriangleup", "\\bigtriangleup"),
                entry("symbols_binary_bigtriangledown", "\\bigtriangledown"),
                entry("symbols_binary_amalg", "\\amalg")),
            section("symbols_relations",
                entry("symbols_relations_lt", "<"),
                entry("symbols_relations_gt", ">"),
                entry("symbols_relations_equals", "="),
                entry("symbols_relations_leq", "\\leq"),
                entry("symbols_relations_geq", "\\geq"),
                entry("symbols_relations_equiv", "\\equiv"),
                entry("symbols_relations_ll", "\\ll"),
                entry("symbols_relations_gg", "\\gg"),
                entry("symbols_relations_doteq", "\\doteq"),
                entry("symbols_relations_prec", "\\prec"),
                entry("symbols_relations_succ", "\\succ"),
                entry("symbols_relations_sim", "\\sim"),
                entry("symbols_relations_preceq", "\\preceq"),
                entry("symbols_relations_succeq", "\\succeq"),
                entry("symbols_relations_simeq", "\\simeq"),
                entry("symbols_relations_approx", "\\approx"),
                entry("symbols_relations_subset", "\\subset"),
                entry("symbols_relations_supset", "\\supset"),
                entry("symbols_relations_subseteq", "\\subseteq"),
                entry("symbols_relations_supseteq", "\\supseteq"),
                entry("symbols_relations_sqsubset", "\\sqsubset"),
                entry("symbols_relations_sqsupset", "\\sqsupset"),
                entry("symbols_relations_sqsubseteq", "\\sqsubseteq"),
                entry("symbols_relations_sqsupseteq", "\\sqsupseteq"),
                entry("symbols_relations_cong", "\\cong"),
                entry("symbols_relations_bowtie", "\\bowtie"),
                entry("symbols_relations_propto", "\\propto"),
                entry("symbols_relations_in", "\\in"),
                entry("symbols_relations_ni", "\\ni"),
                entry("symbols_relations_vdash", "\\vdash"),
                entry("symbols_relations_dashv", "\\dashv"),
                entry("symbols_relations_models", "\\models"),
                entry("symbols_relations_mid", "\\mid"),
                entry("symbols_relations_parallel", "\\parallel"),
                entry("symbols_relations_perp", "\\perp"),
                entry("symbols_relations_smile", "\\smile"),
                entry("symbols_relations_frown", "\\frown"),
                entry("symbols_relations_asymp", "\\asymp"),
                entry("symbols_relations_notin", "\\notin"),
                entry("symbols_relations_neq", "\\neq")),
            section("symbols_arrows",
                entry("symbols_arrows_leftarrow", "\\leftarrow"),
                entry("symbols_arrows_rightarrow", "\\rightarrow"),
                entry("symbols_arrows_gets", "\\gets"),
                entry("symbols_arrows_to", "\\to"),
                entry("symbols_arrows_uparrow", "\\uparrow"),
                entry("symbols_arrows_downarrow", "\\downarrow"),
                entry("symbols_arrows_leftrightarrow", "\\leftrightarrow"),
                entry("symbols_arrows_Uparrow", "\\Uparrow"),
                entry("symbols_arrows_Downarrow", "\\Downarrow"),
                entry("symbols_arrows_updownarrow", "\\updownarrow"),
                entry("symbols_arrows_Updownarrow", "\\Updownarrow"),
                entry("symbols_arrows_longleftarrow", "\\longleftarrow"),
                entry("symbols_arrows_longrightarrow", "\\longrightarrow"),
                entry("symbols_arrows_Leftarrow", "\\Leftarrow"),
                entry("symbols_arrows_Rightarrow", "\\Rightarrow"),
                entry("symbols_arrows_Longleftarrow", "\\Longleftarrow"),
                entry("symbols_arrows_Longrightarrow", "\\Longrightarrow"),
                entry("symbols_arrows_Leftrightarrow", "\\Leftrightarrow"),
                entry("symbols_arrows_Longleftrightarrow", "\\Longleftrightarrow"),
                entry("symbols_arrows_mapsto", "\\mapsto"),
                entry("symbols_arrows_longmapsto", "\\longmapsto"),
                entry("symbols_arrows_hookleftarrow", "\\hookleftarrow"),
                entry("symbols_arrows_hookrightarrow", "\\hookrightarrow"),
                entry("symbols_arrows_nearrow", "\\nearrow"),
                entry("symbols_arrows_searrow", "\\searrow"),
                entry("symbols_arrows_swarrow", "\\swarrow"),
                entry("symbols_arrows_nwarrow", "\\nwarrow"),
                entry("symbols_arrows_rightleftharpoons", "\\rightleftharpoons"),
                entry("symbols_arrows_leftrightharpoons", "\\leftrightharpoons"),
                entry("symbols_arrows_leftleftarrows", "\\leftleftarrows"),
                entry("symbols_arrows_rightrightarrows", "\\rightrightarrows")),
            section("symbols_others",
                entry("symbols_others_therefore", "\\therefore"),
                entry("symbols_others_because", "\\because"),
                entry("symbols_others_ldots", "\\ldots"),
                entry("symbols_others_cdots", "\\cdots"),
                entry("symbols_others_vdots", "\\vdots"),
                entry("symbols_others_ddots", "\\ddots"),
                entry("symbols_others_forall", "\\forall"),
                entry("symbols_others_exists", "\\exists"),
                entry("symbols_others_nexists", "\\nexists"),
                entry("symbols_others_neg", "\\neg"),
                entry("symbols_others_emptyset", "\\emptyset"),
                entry("symbols_others_infty", "\\infty"),
                entry("symbols_others_nabla", "\\nabla"),
                entry("symbols_others_triangle", "\\triangle"),
                entry("symbols_others_square", "\\square"),
                entry("symbols_others_lozenge", "\\lozenge"),
                entry("symbols_others_top", "\\top"),
                entry("symbols_others_bot", "\\bot"),
                entry("symbols_others_angle", "\\angle"),
                entry("symbols_others_measuredangle", "\\measuredangle"),
                entry("symbols_others_surd", "\\surd"),
                entry("symbols_others_heartsuit", "\\heartsuit"),
                entry("symbols_others_diamondsuit", "\\diamondsuit"),
                entry("symbols_others_clubsuit", "\\clubsuit"),
                entry("symbols_others_spadesuit", "\\spadesuit"),
                entry("symbols_others_flat", "\\flat"),
                entry("symbols_others_natural", "\\natural"),
                entry("symbols_others_sharp", "\\sharp"))),
        category("greek", "\\alpha\\textcolor{#4d7b32}{\\beta}\\quad\\textcolor{#4d7b32}{\\gamma}\\delta",
            section("greek_lowercase",
                entry("greek_lowercase_alpha", "\\alpha"),
                entry("greek_lowercase_beta", "\\beta"),
                entry("greek_lowercase_gamma", "\\gamma"),
                entry("greek_lowercase_delta", "\\delta"),
                entry("greek_lowercase_epsilon", "\\epsilon"),
                entry("greek_lowercase_varepsilon", "\\varepsilon"),
                entry("greek_lowercase_zeta", "\\zeta"),
                entry("greek_lowercase_eta", "\\eta"),
                entry("greek_lowercase_theta", "\\theta"),
                entry("greek_lowercase_vartheta", "\\vartheta"),
                entry("greek_lowercase_iota", "\\iota"),
                entry("greek_lowercase_kappa", "\\kappa"),
                entry("greek_lowercase_lambda", "\\lambda"),
                entry("greek_lowercase_mu", "\\mu"),
                entry("greek_lowercase_nu", "\\nu"),
                entry("greek_lowercase_xi", "\\xi"),
                entry("greek_lowercase_omicron", "\\omicron"),
                entry("greek_lowercase_pi", "\\pi"),
                entry("greek_lowercase_varpi", "\\varpi"),
                entry("greek_lowercase_rho", "\\rho"),
                entry("greek_lowercase_varrho", "\\varrho"),
                entry("greek_lowercase_sigma", "\\sigma"),
                entry("greek_lowercase_varsigma", "\\varsigma"),
                entry("greek_lowercase_tau", "\\tau"),
                entry("greek_lowercase_upsilon", "\\upsilon"),
                entry("greek_lowercase_phi", "\\phi"),
                entry("greek_lowercase_varphi", "\\varphi"),
                entry("greek_lowercase_chi", "\\chi"),
                entry("greek_lowercase_psi", "\\psi"),
                entry("greek_lowercase_omega", "\\omega")),
            section("greek_uppercase",
                entry("greek_uppercase_Gamma", "\\Gamma"),
                entry("greek_uppercase_Delta", "\\Delta"),
                entry("greek_uppercase_Theta", "\\Theta"),
                entry("greek_uppercase_Lambda", "\\Lambda"),
                entry("greek_uppercase_Xi", "\\Xi"),
                entry("greek_uppercase_Pi", "\\Pi"),
                entry("greek_uppercase_Sigma", "\\Sigma"),
                entry("greek_uppercase_Upsilon", "\\Upsilon"),
                entry("greek_uppercase_Phi", "\\Phi"),
                entry("greek_uppercase_Psi", "\\Psi"),
                entry("greek_uppercase_Omega", "\\Omega")),
            section("greek_letters",
                entry("greek_letters_hbar", "\\hbar"),
                entry("greek_letters_imath", "\\imath"),
                entry("greek_letters_jmath", "\\jmath"),
                entry("greek_letters_ell", "\\ell"),
                entry("greek_letters_Re", "\\Re"),
                entry("greek_letters_Im", "\\Im"),
                entry("greek_letters_aleph", "\\aleph"),
                entry("greek_letters_beth", "\\beth"),
                entry("greek_letters_gimel", "\\gimel"),
                entry("greek_letters_daleth", "\\daleth"),
                entry("greek_letters_wp", "\\wp"),
                entry("greek_letters_mho", "\\mho"),
                entry("greek_letters_partial", "\\partial"),
                entry("greek_letters_eth", "\\eth"),
                entry("greek_letters_S", "\\S"),
                entry("greek_letters_font_mathrm", "\\mathrm{ABC}"),
                entry("greek_letters_font_mathbb", "\\mathbb{ABC}"),
                entry("greek_letters_font_mathfrak", "\\mathfrak{ABC}"),
                entry("greek_letters_font_mathcal", "\\mathcal{ABC}"),
                entry("greek_letters_font_mathscr", "\\mathscr{ABC}"))),
        category("fraction", "\\frac{x}{\\textcolor{#4d7b32}{y}}",
            section("fraction_fractions",
                entry("fraction_fractions_fraction", "\\frac{a}{b}"),
                entry("fraction_fractions_mixed", "x\\frac{a}{b}"),
                entry("fraction_fractions_differential", "\\mathrm{d}t"),
                entry("fraction_fractions_derivative", "\\frac{\\mathrm{d}y}{\\mathrm{d}x}"),
                entry("fraction_fractions_partial", "\\partial t"),
                entry("fraction_fractions_partial_fraction", "\\frac{\\partial y}{\\partial x}"),
                entry("fraction_fractions_gradient", "\\nabla\\psi"),
                entry("fraction_fractions_second_partial", "\\frac{\\partial^2 y}{\\partial x_1\\partial x_2}"),
                entry("fraction_fractions_continued", "\\frac{1}{a+\\frac{7}{b+\\frac{2}{9}}}=c"),
                entry("fraction_fractions_cfrac", "x=a_0+\\cfrac{1}{a_1+\\cfrac{1}{a_2+\\cfrac{1}{a_3}}}")),
            section("fraction_derivatives",
                entry("fraction_derivatives_dot", "\\dot{a}"),
                entry("fraction_derivatives_ddot", "\\ddot{a}"),
                entry("fraction_derivatives_prime", "f'"),
                entry("fraction_derivatives_double_prime", "f''"),
                entry("fraction_derivatives_nth", "f^{(n)}")),
            section("fraction_modular",
                entry("fraction_modular_bmod", "a\\bmod b"),
                entry("fraction_modular_pmod", "a\\equiv b\\pmod m"),
                entry("fraction_modular_gcd", "\\gcd(m,n)"),
                entry("fraction_modular_lcm", "\\operatorname{lcm}(m,n)"))),
        category("radical", "\\textcolor{#4d7b32}{\\sqrt{}}e^x",
            section("radical_roots",
                entry("radical_roots_root", "\\sqrt{x}"),
                entry("radical_roots_nth_root", "\\sqrt[n]{x}")),
            section("radical_scripts",
                entry("radical_scripts_power", "x^{a}"),
                entry("radical_scripts_subscript", "x_{a}"),
                entry("radical_scripts_both", "x_{a}^{b}"),
                entry("radical_scripts_prescript", "{}_{a}^{b}x"),
                entry("radical_scripts_nested", "{}_{a}^{1}x_{3}^{4}")),
            section("radical_accents",
                entry("radical_accents_hat", "\\hat{a}"),
                entry("radical_accents_check", "\\check{a}"),
                entry("radical_accents_grave", "\\grave{a}"),
                entry("radical_accents_acute", "\\acute{a}"),
                entry("radical_accents_tilde", "\\tilde{a}"),
                entry("radical_accents_breve", "\\breve{a}"),
                entry("radical_accents_bar", "\\bar{a}"),
                entry("radical_accents_vec", "\\vec{a}"),
                entry("radical_accents_dot", "\\dot{a}"),
                entry("radical_accents_ddot", "\\ddot{a}"),
                entry("radical_accents_degree", "37^{\\circ}"),
                entry("radical_accents_widehat", "\\widehat{abc}"),
                entry("radical_accents_widetilde", "\\widetilde{abc}"),
                entry("radical_accents_overleftarrow", "\\overleftarrow{abc}"),
                entry("radical_accents_overrightarrow", "\\overrightarrow{abc}"),
                entry("radical_accents_overline", "\\overline{abc}"),
                entry("radical_accents_underline", "\\underline{abc}"),
                entry("radical_accents_overbrace", "\\overbrace{abc}"),
                entry("radical_accents_underbrace", "\\underbrace{abc}"))),
        category("limit", "\\textcolor{#4d7b32}{\\lim}_{n\\to\\infty}",
            section("limit_limits",
                entry("limit_limits_lim", "\\lim a"),
                entry("limit_limits_limit", "\\lim_{x\\to 0}{a}"),
                entry("limit_limits_infinite", "\\lim_{x\\to\\infty}{a}"),
                entry("limit_limits_inline", "\\lim\\nolimits_{x\\to0}a"),
                entry("limit_limits_max_limits", "\\max_{x} a"),
                entry("limit_limits_min_limits", "\\min_{x} a")),
            section("limit_logarithms",
                entry("limit_logarithms_log", "\\log_{a} b"),
                entry("limit_logarithms_lg", "\\lg b"),
                entry("limit_logarithms_ln", "\\ln b"),
                entry("limit_logarithms_exp", "\\exp a")),
            section("limit_bounds",
                entry("limit_bounds_min", "\\min x"),
                entry("limit_bounds_max", "\\max x"),
                entry("limit_bounds_sup", "\\sup x"),
                entry("limit_bounds_inf", "\\inf x"),
                entry("limit_bounds_lim", "\\lim x"),
                entry("limit_bounds_limsup", "\\limsup x"),
                entry("limit_bounds_liminf", "\\liminf x"),
                entry("limit_bounds_dim", "\\dim x"),
                entry("limit_bounds_ker", "\\ker x"))),
        category("trig", "\\textcolor{#4d7b32}{\\sin}\\alpha",
            section("trig_trigonometric",
                entry("trig_trigonometric_sin", "\\sin\\alpha"),
                entry("trig_trigonometric_cos", "\\cos\\alpha"),
                entry("trig_trigonometric_tan", "\\tan\\alpha"),
                entry("trig_trigonometric_cot", "\\cot\\alpha"),
                entry("trig_trigonometric_sec", "\\sec\\alpha"),
                entry("trig_trigonometric_csc", "\\csc\\alpha")),
            section("trig_inverse_trig",
                entry("trig_inverse_trig_sin_inverse", "\\sin^{-1}\\alpha"),
                entry("trig_inverse_trig_cos_inverse", "\\cos^{-1}\\alpha"),
                entry("trig_inverse_trig_tan_inverse", "\\tan^{-1}\\alpha"),
                entry("trig_inverse_trig_cot_inverse", "\\cot^{-1}\\alpha"),
                entry("trig_inverse_trig_sec_inverse", "\\sec^{-1}\\alpha"),
                entry("trig_inverse_trig_csc_inverse", "\\csc^{-1}\\alpha"),
                entry("trig_inverse_trig_arcsin", "\\arcsin a"),
                entry("trig_inverse_trig_arccos", "\\arccos a"),
                entry("trig_inverse_trig_arctan", "\\arctan a"),
                entry("trig_inverse_trig_arccot", "\\operatorname{arccot} a"),
                entry("trig_inverse_trig_arcsec", "\\operatorname{arcsec} a"),
                entry("trig_inverse_trig_arccsc", "\\operatorname{arccsc} a")),
            section("trig_hyperbolic",
                entry("trig_hyperbolic_sinh", "\\sinh\\alpha"),
                entry("trig_hyperbolic_cosh", "\\cosh\\alpha"),
                entry("trig_hyperbolic_tanh", "\\tanh\\alpha"),
                entry("trig_hyperbolic_coth", "\\coth\\alpha"),
                entry("trig_hyperbolic_sech", "\\operatorname{sech}\\alpha"),
                entry("trig_hyperbolic_csch", "\\operatorname{csch}\\alpha")),
            section("trig_inverse_hyperbolic",
                entry("trig_inverse_hyperbolic_sinh_inverse", "\\operatorname{sinh}^{-1}\\alpha"),
                entry("trig_inverse_hyperbolic_cosh_inverse", "\\operatorname{cosh}^{-1}\\alpha"),
                entry("trig_inverse_hyperbolic_tanh_inverse", "\\operatorname{tanh}^{-1}\\alpha"),
                entry("trig_inverse_hyperbolic_coth_inverse", "\\operatorname{coth}^{-1}\\alpha"),
                entry("trig_inverse_hyperbolic_sech_inverse", "\\operatorname{sech}^{-1}\\alpha"),
                entry("trig_inverse_hyperbolic_csch_inverse", "\\operatorname{csch}^{-1}\\alpha"))),
        category("integral", "\\textcolor{#4d7b32}{\\int}_a^b",
            section("integral_int",
                entry("integral_int_int", "\\int"),
                entry("integral_int_int_bounds", "\\int_{a}^{b}"),
                entry("integral_int_int_limits", "\\int\\limits_{a}^{b}")),
            section("integral_iint",
                entry("integral_iint_iint", "\\iint"),
                entry("integral_iint_iint_bounds", "\\iint_{a}^{b}"),
                entry("integral_iint_iint_limits", "\\iint\\limits_{a}^{b}")),
            section("integral_iiint",
                entry("integral_iiint_iiint", "\\iiint"),
                entry("integral_iiint_iiint_bounds", "\\iiint_{a}^{b}"),
                entry("integral_iiint_iiint_limits", "\\iiint\\limits_{a}^{b}")),
            section("integral_contour",
                entry("integral_contour_oint", "\\oint"),
                entry("integral_contour_oint_c", "\\oint_C"))),
        category("operators", "\\textcolor{#4d7b32}{\\sum}_{i=0}^{n}",
            section("operators_sum",
                entry("operators_sum_sum", "\\sum"),
                entry("operators_sum_sum_limits", "\\sum_{a}^{b}"),
                entry("operators_sum_sum_inline", "\\sum\\nolimits_{a}^{b}")),
            section("operators_prod",
                entry("operators_prod_prod", "\\prod"),
                entry("operators_prod_prod_limits", "\\prod_{a}^{b}"),
                entry("operators_prod_prod_inline", "\\prod\\nolimits_{a}^{b}")),
            section("operators_coprod",
                entry("operators_coprod_coprod", "\\coprod"),
                entry("operators_coprod_coprod_limits", "\\coprod_{a}^{b}"),
                entry("operators_coprod_coprod_inline", "\\coprod\\nolimits_{a}^{b}")),
            section("operators_bigcup",
                entry("operators_bigcup_bigcup", "\\bigcup"),
                entry("operators_bigcup_bigcup_limits", "\\bigcup_{a}^{b}"),
                entry("operators_bigcup_bigcup_inline", "\\bigcup\\nolimits_{a}^{b}")),
            section("operators_bigcap",
                entry("operators_bigcap_bigcap", "\\bigcap"),
                entry("operators_bigcap_bigcap_limits", "\\bigcap_{a}^{b}"),
                entry("operators_bigcap_bigcap_inline", "\\bigcap\\nolimits_{a}^{b}")),
            section("operators_bigvee",
                entry("operators_bigvee_bigvee", "\\bigvee"),
                entry("operators_bigvee_bigvee_limits", "\\bigvee_{a}^{b}"),
                entry("operators_bigvee_bigvee_inline", "\\bigvee\\nolimits_{a}^{b}")),
            section("operators_bigwedge",
                entry("operators_bigwedge_bigwedge", "\\bigwedge"),
                entry("operators_bigwedge_bigwedge_limits", "\\bigwedge_{a}^{b}"),
                entry("operators_bigwedge_bigwedge_inline", "\\bigwedge\\nolimits_{a}^{b}"))),
        category("brackets", "\\textcolor{#4d7b32}{\\{}[( )]\\textcolor{#4d7b32}{\\}}",
            section("brackets_delimiters",
                entry("brackets_delimiters_paren", "\\left( x \\right)"),
                entry("brackets_delimiters_square", "\\left[ x \\right]"),
                entry("brackets_delimiters_angle", "\\left\\langle x \\right\\rangle"),
                entry("brackets_delimiters_brace", "\\left\\{ x \\right\\}"),
                entry("brackets_delimiters_abs", "\\left| x \\right|"),
                entry("brackets_delimiters_norm", "\\left\\| x \\right\\|"),
                entry("brackets_delimiters_floor", "\\left\\lfloor x \\right\\rfloor"),
                entry("brackets_delimiters_ceil", "\\left\\lceil x \\right\\rceil")),
            section("brackets_commons",
                entry("brackets_commons_binom", "\\binom{n}{r}"),
                entry("brackets_commons_interval", "\\left[0,1\\right)"),
                entry("brackets_commons_bra", "\\langle\\psi|"),
                entry("brackets_commons_ket", "|\\psi\\rangle"),
                entry("brackets_commons_inner", "\\langle\\psi|\\phi\\rangle"))),
        category("matrix", "\\begin{bmatrix}0 & 1\\\\1 & 0\\end{bmatrix}",
            section("matrix_matrices",
                entry("matrix_matrices_matrix", "\\begin{matrix}a & b \\\\ c & d\\end{matrix}"),
                entry("matrix_matrices_bmatrix", "\\begin{bmatrix}a & b \\\\ c & d\\end{bmatrix}"),
                entry("matrix_matrices_pmatrix", "\\begin{pmatrix}a & b \\\\ c & d\\end{pmatrix}"),
                entry("matrix_matrices_vmatrix", "\\begin{vmatrix}a & b \\\\ c & d\\end{vmatrix}"),
                entry("matrix_matrices_Vmatrix", "\\begin{Vmatrix}a & b \\\\ c & d\\end{Vmatrix}"),
                entry("matrix_matrices_Bmatrix", "\\begin{Bmatrix}a & b \\\\ c & d\\end{Bmatrix}"),
                entry("matrix_matrices_dots_matrix", "\\begin{pmatrix}a_{11} & \\cdots & a_{1n}\\\\\\vdots & \\ddots & \\vdots\\\\a_{n1} & \\cdots & a_{nn}\\end{pmatrix}")),
            section("matrix_arrays",
                entry("matrix_arrays_array", "\\begin{array}{cc}a & b\\\\c & d\\end{array}"),
                entry("matrix_arrays_cases", "\\begin{cases}x & x>0\\\\-x & x\\leq 0\\end{cases}"),
                entry("matrix_arrays_aligned", "\\begin{aligned}y&=1729x\\\\y&=x\\end{aligned}"))));
}
